# Generated by Django 2.2.16 on 2020-09-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0003_auto_20200905_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id_comercio', models.IntegerField(db_column='id_comercio_PK', editable=False, primary_key=True, serialize=False, verbose_name='ID Comercio')),
                ('razon_social', models.CharField(blank=True, db_column='razon_social', max_length=100, null=True, verbose_name='Razon Social')),
                ('razon_comercial', models.CharField(db_column='razon_comercial', max_length=100, verbose_name='Razon Comercial')),
                ('nit', models.IntegerField(db_column='nit', unique=True, verbose_name='NIT')),
                ('pbx', models.CharField(blank=True, db_column='pbx', max_length=10, null=True, verbose_name='PBX')),
            ],
            options={
                'verbose_name': 'comercio',
                'verbose_name_plural': 'comercios',
                'db_table': 'tbl_comercio',
            },
        ),
        migrations.CreateModel(
            name='TipoComercio',
            fields=[
                ('id_tipo_comercio', models.IntegerField(db_column='id_tipo_comercio_PK', editable=False, primary_key=True, serialize=False, verbose_name='ID Tipo Comercio')),
                ('tipo_comercio', models.CharField(db_column='tipo_comercio', max_length=50, unique=True, verbose_name='Tipo Comercio')),
            ],
            options={
                'verbose_name': 'tipo comercio',
                'verbose_name_plural': 'tipos de comercio',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(db_column='id_sucursal_PK', editable=False, primary_key=True, serialize=False, verbose_name='ID Sucursal')),
                ('nombre_sucursal', models.CharField(db_column='nombre_sucursal', max_length=200, verbose_name='Sucursal')),
                ('zona', models.IntegerField(db_column='zona', unique=True, verbose_name='Zona')),
                ('direccion', models.CharField(db_column='direccion', max_length=250, verbose_name='dirección')),
                ('referencia', models.CharField(blank=True, db_column='referencia', help_text='De una referencia de la ubicación de la sucursal', max_length=400, null=True, verbose_name='Referencia')),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=10, null=True, verbose_name='Telefono')),
                ('id_comercio', models.ForeignKey(db_column='id_comercio_FK', on_delete='CASCADE', to='comercio.Comercio', verbose_name='Comercio')),
                ('id_depto', models.ForeignKey(db_column='id_depto_FK', help_text='Departamento donde se ubica el comercio', on_delete='CASCADE', to='ubicacion.Departamento', verbose_name='Departamento')),
                ('id_muni', models.ForeignKey(db_column='id_muni_FK', help_text='Municipio donde se ubica el comercio', on_delete='CASCADE', to='ubicacion.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'tbl_sucursal',
                'unique_together': {('id_comercio', 'nombre_sucursal')},
            },
        ),
    ]
