# Generated by Django 2.2.16 on 2020-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_remove_sucursal_id_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='zona',
            field=models.IntegerField(db_column='zona', verbose_name='Zona'),
        ),
    ]
