# Generated by Django 2.2.16 on 2020-09-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_auto_20200918_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='id_depto',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_comercio',
            field=models.ForeignKey(db_column='id_comercio_FK', on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio', verbose_name='Comercio'),
        ),
    ]
