# Generated by Django 2.2.16 on 2020-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_auto_20200905_0056'),
        ('comercio', '0005_auto_20200918_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='id_depto',
            field=models.ForeignKey(db_column='id_depto_FK', default=1, help_text='Departamento donde se ubica el comercio', on_delete='CASCADE', to='ubicacion.Departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
