# Generated by Django 2.2.16 on 2020-09-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0006_sucursal_id_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id_depto',
            field=models.ForeignKey(db_column='id_depto_FK', help_text='Departamento donde se ubica el comercio', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_muni',
            field=models.ForeignKey(db_column='id_muni_FK', help_text='Municipio donde se ubica el comercio', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Municipio', verbose_name='Municipio'),
        ),
    ]
