# Generated by Django 2.2.16 on 2020-09-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0005_auto_20200926_1813'),
        ('comercio', '0007_auto_20200919_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
