# Generated by Django 2.2.16 on 2020-09-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0008_delete_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='id_comercio',
            field=models.AutoField(db_column='id_comercio_PK', editable=False, primary_key=True, serialize=False, verbose_name='ID Comercio'),
        ),
    ]
