# Generated by Django 2.2.16 on 2020-09-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.IntegerField(db_column='id_depto_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Departamento')),
                ('nombre_depto', models.IntegerField(db_column='nombre_depto', max_length=50, unique=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'db_table': 'tbl_depto',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='id_region_PK', editable=False, primary_key=True, serialize=False, verbose_name='No. Region')),
                ('nombre_region', models.CharField(db_column='nombre_region', help_text='Ingrese: Norte, Centro, Sur, Oriente, Occidente', max_length=25, unique=True, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'db_table': 'tbl_region',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.IntegerField(db_column='id_muni_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Municipio')),
                ('nombre_muni', models.CharField(db_column='nombre_muni', max_length=50, verbose_name='Municipio')),
                ('id_depto', models.ForeignKey(db_column='id_depto_FK', on_delete='CASCADE', to='ubicacion.Departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'municipios',
                'db_table': 'tbl_muni',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_region',
            field=models.ForeignKey(db_column='id_region_FK', on_delete='CASCADE', to='ubicacion.Region', verbose_name='Region'),
        ),
    ]
