# Generated by Django 2.2.16 on 2020-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre_depto',
            field=models.CharField(db_column='nombre_depto', max_length=50, unique=True, verbose_name='Departamento'),
        ),
    ]
