# Generated by Django 2.2.16 on 2020-09-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_auto_20200904_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'municipio', 'verbose_name_plural': 'municipios'},
        ),
    ]
