# Generated by Django 2.2.16 on 2020-09-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_auto_20200905_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_depto',
            field=models.AutoField(db_column='id_depto_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id_muni',
            field=models.AutoField(db_column='id_muni_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Municipio'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(db_column='id_region_PK', editable=False, primary_key=True, serialize=False, verbose_name='No. Region'),
        ),
    ]
