# Generated by Django 2.2.16 on 2020-09-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_frmqueja', models.IntegerField(db_column='id_frmqueja_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Queja')),
                ('fecha_registro', models.DateField(auto_now=True, db_column='fecha_registro', verbose_name='Fecha Queja')),
                ('nombre_cliente', models.CharField(blank=True, db_column='nombre', default='Anónimo', help_text='Opcional', max_length=50, null=True, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(blank=True, db_column='apellido', default='Anónimo', help_text='Opcional', max_length=50, null=True, verbose_name='Apellido')),
                ('fecha_incidente', models.DateField(db_column='fecha_incidente', verbose_name='Fecha del Incidente')),
                ('factura', models.CharField(db_column='factura', help_text='No. de factura del comercio', max_length=50, verbose_name='Factura')),
                ('detalle_queja', models.TextField(db_column='detalle_queja', verbose_name='Detalle de la queja')),
                ('solicitud', models.TextField(db_column='solcitud', help_text='Explique su sugerencia o solicitud', verbose_name='Solicitud')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal_FK', help_text='Ingrese datos del comercio', on_delete='CASCADE', to='comercio.Sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'queja',
                'verbose_name_plural': 'quejas',
                'db_table': 'tbl_formulario',
            },
        ),
    ]
