# Generated by Django 2.2.16 on 2020-09-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_auto_20200919_1645'),
        ('frmqueja', '0002_auto_20200918_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='id_comercio',
            field=models.ForeignKey(db_column='id_comercio_FK', default=1, on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio', verbose_name='Comercio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal_FK', on_delete=django.db.models.deletion.CASCADE, to='comercio.Sucursal', verbose_name='Sucursal'),
        ),
    ]
