# Generated by Django 2.2.16 on 2020-09-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0004_auto_20200926_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id_sucursal',
        ),
        migrations.AddField(
            model_name='formulario',
            name='direccion',
            field=models.CharField(db_column='direccion', default=1, max_length=250, verbose_name='dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_sucursal',
            field=models.CharField(db_column='nombre_sucursal', default=1, max_length=200, verbose_name='Sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='referencia',
            field=models.CharField(blank=True, db_column='referencia', help_text='De una referencia de la ubicación de la sucursal', max_length=400, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(blank=True, db_column='telefono', max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='zona',
            field=models.IntegerField(db_column='zona', default=1, verbose_name='Zona'),
            preserve_default=False,
        ),
    ]
