# Generated by Django 2.2.16 on 2020-09-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0005_auto_20200926_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='referencia',
            field=models.CharField(blank=True, db_column='referencia', max_length=400, null=True, verbose_name='Referencia'),
        ),
    ]
