# Generated by Django 2.2.16 on 2020-09-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0006_auto_20200926_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id_frmqueja',
            field=models.AutoField(db_column='id_frmqueja_PK', editable=False, primary_key=True, serialize=False, verbose_name='Id Queja'),
        ),
    ]
