# Generated by Django 2.2.16 on 2020-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0007_auto_20200926_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='id_region',
            field=models.CharField(blank=True, db_column='region', editable=False, max_length=25, null=True, verbose_name='Region'),
        ),
    ]
