# Generated by Django 2.2.16 on 2020-09-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frmqueja', '0008_formulario_id_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='id_region',
            new_name='region',
        ),
    ]
